
include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

stages:
  - test

test:extra-tools:
  image: "python:3"
  stage: test

  before_script:
    # Rename the branch we're on, so that it's not in the way for the
    # subsequent fetch. It's ok if this fails, it just means we're not on any
    # branch.
    - git branch -m temp-branch || true
    # Set up git identity
    - git config --global user.name "Northern.tech" && git config --global user.email "info@northern.tech"

  script:
    # Check changelog-generator test.
    - ( cd extra/changelog-generator && ./test-changelog-generator )
