version: '2'
services:

    #
    # mender-deployments
    #
    mender-deployments:
        # S3 access configuration - override with your own values
        # Keys have to grant access to default bucket: mender-artifact-storage
        environment:
            DEPLOYMENTS_AWS_AUTH_KEY: ${AWS_ACCESS_KEY_ID}
            DEPLOYMENTS_AWS_AUTH_SECRET: ${AWS_SECRET_ACCESS_KEY}
            DEPLOYMENTS_AWS_URI: https://s3.amazonaws.com
