version: '2'
services:

    #
    # mender-deployments
    #
    mender-deployments:
        image: mendersoftware/deployments:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo-deployments

    mender-mongo-deployments:
        image: mongo:3.4
        networks:
            mender:
                aliases:
                    - mongo-deployments

    #
    # mender-gui
    #
    mender-gui:
        image: mendersoftware/gui:latest
        networks:
            - mender

    #
    # mender-api-gateway
    #
    mender-api-gateway:
        image: mendersoftware/api-gateway:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        # critical - otherwise nginx may not detect
        # these servers and exits with 'upstream server not found'
        depends_on:
            - mender-device-auth
            - mender-device-adm
            - mender-deployments
            - mender-gui
            - mender-useradm
            - mender-inventory

    #
    # mender-device-auth
    #
    mender-device-auth:
        image: mendersoftware/deviceauth:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo-device-auth

    mender-mongo-device-auth:
        image: mongo:3.4
        networks:
            mender:
                aliases:
                    - mongo-device-auth

    #
    # mender-device-adm
    #
    mender-device-adm:
        image: mendersoftware/deviceadm:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo-device-adm

    mender-mongo-device-adm:
        image: mongo:3.4
        networks:
            mender:
                aliases:
                    - mongo-device-adm

    #
    # mender-inventory
    #
    mender-inventory:
        image: mendersoftware/inventory:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo-inventory

    mender-mongo-inventory:
        image: mongo:3.4
        networks:
            mender:
                aliases:
                    - mongo-inventory

    #
    # mender-useradm
    #
    mender-useradm:
        image: mendersoftware/useradm:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo-useradm

    mender-mongo-useradm:
        image: mongo:3.4
        networks:
            mender:
                aliases:
                    - mongo-useradm

networks:
    mender:
