version: '2.1'
services:

    #
    # mender-client
    #
    mender-client:
        image: mendersoftware/mender-client-qemu:internal-v2020.02
        networks:
            - mender
        stdin_open: true
        tty: true
        privileged: true
