version: '2'
services:
    #
    # mender-deployments
    #
    mender-deployments:
        image: mendersoftware/deployments:latest
        ports:
            - "8080:8080"
        networks:
            - mender
        # Application requires S3 access.
        # For convinience access can be configured here to overide config file.
        # Keys have to grant access to default bucket: mender-artifact-storage
        # Otherwhise provide config file though volume.
        #
        # environment:
        #     AWS_ACCESS_KEY_ID: my-key-123
        #     AWS_SECRET_ACCESS_KEY: my-key-123
        depends_on:
            - mender-mongo-deployments

    mender-mongo-deployments:
        image: mongo:latest
        networks:
            mender:
                aliases:
                    - mongo-deployments

        ports:
            - "27018:27017"

    #
    # mender-etcd
    #
    mender-etcd:
        image: microbox/etcd:latest
        ports:
            - "4001:4001"
            - "7001:7001"
        volumes:
            - /var/etcd/:/data
        #override command since the image entrypoint requires
        #these two args
        command:
            - -data-dir=/data
            - -name=mender-etcd
        networks:
            mender:
                aliases:
                    - etcd

    #
    # mender-gui
    #
    mender-gui:
        image: mendersoftware/gui:latest
        ports:
            - "8081:80"
        networks:
            - mender

    #
    # mender-api-gateway
    #
    mender-api-gateway:
        image: mendersoftware/api-gateway:latest
        ports:
            - "9080:80"
        networks:
            mender:
                aliases:
                    - gateway
        # nginx doesn't know the actual outside port
        # could be solved with introspection (mapping daemon socket + 'docker ps')
        # the easier way is an env var
        environment:
            MAPPED_PORT: 9080
        # critical - otherwise nginx may not detect
        # these servers and exits with 'upstream server not found'
        depends_on:
            - mender-device-auth
            - mender-device-adm
            - mender-deployments
            - mender-gui

    #
    # mender-device-auth
    #
    mender-device-auth:
        image: mendersoftware/deviceauth:latest
        extends:
            file: common.yml
            service: mender-base
        ports:
            - "8083:8080"
        networks:
            - mender
        depends_on:
            - mender-mongo-device-auth

    mender-mongo-device-auth:
        image: mongo:latest
        networks:
            mender:
                aliases:
                    - mongo-device-auth

        ports:
            - "27019:27017"

    #
    # mender-device-adm
    #
    mender-device-adm:
        image: mendersoftware/deviceadm:latest
        extends:
            file: common.yml
            service: mender-base
        ports:
            - "8082:8080"
        networks:
            - mender
        depends_on:
            - mender-mongo-device-adm

    mender-mongo-device-adm:
        image: mongo:latest
        networks:
            mender:
                aliases:
                    - mongo-device-adm

        ports:
            - "27017:27017"

networks:
    mender:
