version: '2'
services:
    #
    # mender-deployments
    #
    mender-deployments:
        image: mendersoftware/deployments:latest
        ports:
            - "8080:8080"
        container_name: mender-deployments

    #
    # mender-api-gateway (dummy impl.)
    #
    mender-api-gateway:
        extends:
            file: common.yml
            service: mender-base
        build:
            context: .
            dockerfile: api-gateway/Dockerfile
        container_name: mender-api-gateway

    #
    # mender-device-auth (dummy impl.)
    #
    mender-device-auth:
        extends:
            file: common.yml
            service: mender-base
        build:
            context: .
            dockerfile: device-auth/Dockerfile
        container_name: mender-device-auth
