version: '2.1'
services:

    #
    # auditlogs
    #
    mender-auditlogs:
        image: registry.mender.io/mendersoftware/auditlogs:mender-master
        networks:
            - mender
        depends_on:
            - mender-mongo
