version: '2'
services:

    mender-useradm:
        volumes:
            - ./keys/useradm/private.key:/etc/useradm/rsa/private.pem

    mender-device-auth:
        volumes:
            - ./keys/deviceauth/private.key:/etc/deviceauth/rsa/private.pem

    mender-api-gateway:
        ports:
            - "8080:443"
            - "443:443"
        networks:
            mender:
                aliases:
                    - docker.mender.io
        # nginx doesn't know the actual outside port
        # could be solved with introspection (mapping daemon socket + 'docker ps')
        # the easier way is an env var
        environment:
            MAPPED_PORT: 8080
        volumes:
            - ./keys/api-gateway/cert.crt:/var/www/mendersoftware/cert/cert.pem
            - ./keys/api-gateway/private.key:/var/www/mendersoftware/cert/key.pem

    storage-proxy:
        ports:
            - "9000:9000"
        networks:
            mender:
                aliases:
                    - s3.docker.mender.io
        environment:

            # use nginx syntax for rate limiting, see
            # https://nginx.org/en/docs/http/ngx_http_core_module.html#limit_rate
            # Examples:
            #   1m - 1MB/s
            #   512k - 512kB/s
            DOWNLOAD_SPEED: 1m
            MAX_CONNECTIONS: 100
        volumes:
            - ./keys/storage-proxy/cert.crt:/var/www/storage-proxy/cert/cert.crt
            - ./keys/storage-proxy/private.key:/var/www/storage-proxy/cert/private.key

    mender-deployments:
        volumes:
            - ./keys/storage-proxy/cert.crt:/etc/ssl/certs/s3.docker.mender.io.crt
        environment:
            STORAGE_BACKEND_CERT: /etc/ssl/certs/s3.docker.mender.io.crt
            DEPLOYMENTS_AWS_AUTH_KEY: minio
            DEPLOYMENTS_AWS_AUTH_SECRET: minio123
            DEPLOYMENTS_AWS_URI: https://s3.docker.mender.io:9000

    minio:
        image: minio/minio:RELEASE.2016-12-13T17-19-42Z
        networks:
            mender:
                aliases:
                    - minio.s3.docker.mender.io
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123

    mender-gui:
        environment:
            - DEMO=1
