version: '2'
services:

    mender-tenantadm:
        image: mendersoftware/tenantadm:master
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo-tenantadm

    mender-mongo-tenantadm:
        image: mongo:3.4
        networks:
            mender:
                aliases:
                    - mongo-tenantadm
