version: '2'
services:
    #
    # mender-deployments
    #
    mender-deployments:
        image: mendersoftware/deployments:latest
        ports:
            - "8080:8080"
        networks:
            - mender

    #
    # mender-etcd
    #
    mender-etcd:
        image: microbox/etcd:latest
        ports:
            - "4001:4001"
            - "7001:7001"
        volumes:
            - /var/etcd/:/data
        #override command since the image entrypoint requires
        #these two args
        command:
            - -data-dir=/data
            - -name=mender-etcd
        networks:
            mender:
                aliases:
                    - etcd

    #
    # mender-gui
    #
    mender-gui:
        image: mendersoftware/gui:latest
        ports:
            - "8081:80"
        networks:
            - mender

    #
    # mender-api-gateway
    #
    mender-api-gateway:
        image: mendersoftware/api-gateway:latest
        ports:
            - "9080:8080"
        networks:
            mender:
                aliases:
                    - gateway

    redis:
        image: redis:latest
        hostname: redis
        ports:
            - "6379:6379"
        networks:
            mender:
                aliases:
                    # API gateway looks for host named
                    # `api-gateway-redis`
                    - api-gateway-redis
    #
    # mender-device-auth
    #
    mender-device-auth:
        image: mendersoftware/deviceauth:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender

networks:
    mender:
