version: '2.1'
services:

    #
    # auditlogs
    #
    mender-auditlogs:
        image: registry.mender.io/mendersoftware/auditlogs:saas-v2020.09.25
        networks:
            - mender
        depends_on:
            - mender-mongo
